### ISSUE TITLE
unable to create first account

### ISSUE THREAD

**Issue by tinkermesomething** [Flomp/wanderer#28] opened 2024-03-25 21:20 UTC
I am unable to create an account after the first install. The only message is "error creating user". 
I've tried looking at the logs but nothing shows.

**Comment by Flomp** [comment] 2024-03-25 21:27
This is likely a duplicate of [this](https://github.com/Flomp/wanderer/issues/14). Please check that your ORIGIN environment variable is set correctly if you are not hosting wanderer at http://localhost:3000.

**Closed** 2024-04-20 11:53 UTC
Labels: duplicate
